In [1]:
# CREATE NUMPY ARRAYS 

In [2]:
# Creation of arrays with evenly spaced values 

In [1]:
import numpy as np
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [4]:
x = range(1, 10)
print(x)

range(1, 10)


In [6]:
x = np.arange(10.4)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [7]:
x = np.arange(0.5, 10.4, 0.8)
print(x)

[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [8]:
x = np.arange(0.5, 10.4, 0.8, int)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
# linspace

In [12]:
import numpy as np

# 50 values between 1 and 10:
print(np.linspace(1, 10))

# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))

# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [19]:
import numpy as np
samples, spacing = np.linspace(1, 10, retstep=True)
print(spacing)

samples, spacing = np.linspace(1, 10, 20, endpoint=True, retstep=True)
print(spacing)

samples, spacing = np.linspace(1,10,20, endpoint=False, retstep=True)
print(spacing)


0.1836734693877551
0.47368421052631576
0.45


In [20]:
# Zero-Demensional Arrays in Numpy

In [21]:
import numpy as np
x = np.array(42)
print("x ", x)
print("The type of x: ", type(x))
print("The dimension of x:", np.ndim(x))

x  42
The type of x:  <class 'numpy.ndarray'>
The dimension of x: 0


In [1]:
# one-dimensional arrays 

In [4]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
V = np.array([3.4, 6.9, 99.8, 12.8])
print("F: ", F)
print("V", V)
print("Type of F:", F.dtype)
print("Type of V:", V.dtype)
print("Dimension of F:", np.ndim(F))
print("Dimension of V:", np.ndim(V))

F:  [ 1  1  2  3  5  8 13 21]
V [ 3.4  6.9 99.8 12.8]
Type of F: int64
Type of V: float64
Dimension of F: 1
Dimension of V: 1


In [5]:
# Two - and multidimensional Arrays 

In [7]:
A = np.array([[3.4, 8.7, 9.9], 
             [1.1, -7.8, -0.7], 
             [4.1, 12.3, 4.8]])
print(A)
print(A.ndim)

[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]]
2


In [8]:
B = np.array([ [[111, 112], [121, 122]], 
              [[211, 212], [221, 222]], 
              [[331, 312], [321, 322]]])

print(B)
print(B.ndim)

[[[111 112]
  [121 122]]

 [[211 212]
  [221 222]]

 [[331 312]
  [321 322]]]
3


In [9]:
# Shape of an Array 

In [10]:
x = np.array ([ [67, 63, 87], 
                [77, 69, 59], 
                [85, 87, 99], 
                [79, 72, 71], 
                [63, 89, 93], 
                [68, 92, 78]])

print(np.shape(x))

(6, 3)


In [11]:
x.shape = (3, 6)
print(x)

[[67 63 87 77 69 59]
 [85 87 99 79 72 71]
 [63 89 93 68 92 78]]


In [12]:
x.shape = (2, 9)
print(x)

[[67 63 87 77 69 59 85 87 99]
 [79 72 71 63 89 93 68 92 78]]


In [15]:
x = np.array(11)
print(np.shape(x))

()


In [16]:
B = np.array([
        
    [[111, 112, 113], [121, 122, 123]], 
    [[211, 212, 213], [221, 222, 223]], 
    [[311, 312, 313], [321, 322, 323]], 
    [[411, 412, 413], [421, 422, 423]]
    
])

print(B.shape)

(4, 2, 3)


In [17]:
# indexing and slicing 

In [18]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
# print the first element of F 
print(F[0])

# print the last element of F
print(F[-1])

1
21


In [19]:
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7], 
               [4.1, 12.3, 4.8]])

print(A[1][0])

1.1


In [20]:
tmp = A[1]
print(tmp)
print(tmp[0])

[ 1.1 -7.8 -0.7]
1.1


In [21]:
print(A[1, 0])

1.1


In [22]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(S[2:5])
print(S[:4])
print(S[6:])
print(S[:])


[2 3 4]
[0 1 2 3]
[6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [23]:
A = np.array([
    
    [11, 12, 13, 14, 15], 
    [21, 22, 23, 24, 25], 
    [31, 32, 33, 34, 35], 
    [41, 42, 43, 44, 45], 
    [51, 52, 53, 54, 55]])
print(A[:3, 2:])

[[13 14 15]
 [23 24 25]
 [33 34 35]]


In [24]:
print(A[3:, :])

[[41 42 43 44 45]
 [51 52 53 54 55]]


In [25]:
print(A[:, 4:])

[[15]
 [25]
 [35]
 [45]
 [55]]


In [28]:
X = np.arange(28).reshape(4, 7)
print(X)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [29]:
print(X[::2, ::3])

[[ 0  3  6]
 [14 17 20]]


In [30]:
print(X[::, ::3])

[[ 0  3  6]
 [ 7 10 13]
 [14 17 20]
 [21 24 27]]


In [32]:
A = np.array(
        [[ [4, 12, 4], [45, 13, 5], [46, 12, 6]] , 
        [  [46, 14, 4], [45, 14, 5], [46, 11, 5]] , 
        [ [47, 13, 2], [48, 15, 5], [52, 15, 1]] ])
A[1:3, 0:2] # equivalent to A[1:3, 0:2, :]

array([[[46, 14,  4],
        [45, 14,  5]],

       [[47, 13,  2],
        [48, 15,  5]]])

In [2]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
S = A[2:6]
S[0] = 23
S[1] = 23
print(A)

[ 0  1 23 23  4  5  6  7  8  9]


In [4]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
lst2 = lst[2:6]
lst2[0] = 22
lst2[1] = 23
print(lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
np.may_share_memory(A, S)

True

In [6]:
A = np.arange(12)
B = A.reshape(3, 4)
A[0] = 42
print(B)

[[42  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
np.may_share_memory(A,B)

True

In [8]:
# Creating Arrays With Ones, Zeros and Empty

In [1]:
import numpy as np
E = np.ones((2, 3))
print(E)
F = np.ones((3, 4), dtype=int)
print(F)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [2]:
Z = np.zeros((2, 4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
x = np.array([2, 5, 18, 14, 4])
E = np.ones_likes(x)
print(E)
Z = np.zeros_like(x)
print(Z)


AttributeError: module 'numpy' has no attribute 'ones_likes'